/* eslint-disable react-hooks/exhaustive-deps */
import React, { useState, useEffect } from "react";
import { jsPDF } from "jspdf";
import axios from "axios";
import {
  Box,
  Flex,
  Grid,
  GridItem,
  VStack,
  HStack,
  Heading,
  Text,
  Input,
  Button,
  useToast,
} from "@chakra-ui/react";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Line } from "react-chartjs-2";

// Register the necessary components with Chart.js
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

function IntegratedDeFiAdvisor() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [news, setNews] = useState([]);
  const [priceHistory, setPriceHistory] = useState([]);
  const [selectedToken, setSelectedToken] = useState("");
  const toast = useToast();
  const API_BASE_URL = 'http://localhost:8000';

  useEffect(() => {
    addWelcomeMessage();
    fetchDefaultNews();
  }, []);

  useEffect(() => {
    if (selectedToken) {
      fetchTokenNews();
      fetchPriceHistory();
    }
  }, [selectedToken]);

  const addWelcomeMessage = () => {
    setMessages([
      {
        text: "Welcome to your DeFi Advisor! How can I assist you today?",
        sender: "ai",
      },
    ]);
  };

  const handleSend = async () => {
    if (input.trim()) {
      const userMessage = { text: input, sender: "user" };
      setMessages((prev) => [...prev, userMessage]);
      setInput("");

      try {
        const response = await axios.post("http://localhost:3000/api/chat", {
          message: input,
        });
        const { intent, response: aiResponse } = response.data;

        if (intent.token) {
          setSelectedToken(intent.token.toLowerCase());
        }

        const aiMessage = { text: aiResponse, sender: "ai" };
        setMessages((prev) => [...prev, aiMessage]);
      } catch (error) {
        console.error("Error calling AI API:", error);
        toast({
          title: "Error",
          description: "Failed to get AI response. Please try again.",
          status: "error",
          duration: 5000,
          isClosable: true,
        });
      }
    }
  };

  const fetchDefaultNews = async () => {
    try {
      const response = await axios.get(
        "http://localhost:3000/api/news/cryptocurrency"
      );
      setNews(response.data);
    } catch (error) {
      console.error("Error fetching default news:", error);
    }
  };

  const fetchTokenNews = async () => {
    try {
      const response = await axios.get(
        `http://localhost:3000/api/news/${selectedToken}`
      );
      setNews(response.data);
    } catch (error) {
      console.error("Error fetching token-specific news:", error);
    }
  };

  const fetchPriceHistory = async () => {
    try {
      const response = await axios.get(
        `http://localhost:3000/api/price-history/${selectedToken}`
      );
      setPriceHistory(response.data);
    } catch (error) {
      console.error("Error fetching price history:", error);
    }
  };

  const exportToPDF = async () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
  
    // Fonts and Colors
    const userColor = "#d1e7dd";
    const aiColor = "#f8d7da";
    const textColor = "#000";
    const titleColor = "#0d6efd";
  
    // Header
    const addHeader = (page) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(titleColor);
      doc.text("DeFi Advisor - Chat Transcript", 10, 10);
  
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Page ${page}`, pageWidth - 30, 10);
      doc.line(10, 12, pageWidth - 10, 12); // Line below header
    };
  
    // Footer
    const addFooter = () => {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.text("Generated by DeFi Advisor", 10, pageHeight - 10);
    };
  
    let y = 20; // Start height for content
    let page = 1;
  
    // Add header for the first page
    addHeader(page);
  
    // Messages
    messages.forEach((msg, index) => {
      const isUser = msg.sender === "user";
      const bgColor = isUser ? userColor : aiColor;
      const senderLabel = isUser ? "User" : "AI";
  
      // Style message boxes
      const messageBoxWidth = pageWidth - 20;
      const messageHeight = doc.getTextDimensions(msg.text).h + 10;
  
      // Break page if necessary
      if (y + messageHeight > pageHeight - 20) {
        addFooter();
        doc.addPage();
        page++;
        addHeader(page);
        y = 20;
      }
  
      // Draw message box
      doc.setFillColor(bgColor);
      doc.roundedRect(10, y, messageBoxWidth, messageHeight, 3, 3, "F");
  
      // Add sender and text
      doc.setFont("helvetica", "bold");
      doc.setTextColor(textColor);
      doc.text(senderLabel, 12, y + 6);
  
      doc.setFont("helvetica", "normal");
      doc.setTextColor(textColor);
      doc.text(msg.text, 12, y + 12);
  
      y += messageHeight + 5; // Space after each message
    });
  
    // Add footer for the last page
    addFooter();
  
    // Convert the PDF to a Blob and upload it to the server
    const pdfBlob = doc.output('blob');
  
    // Now upload the PDF to Akave and get the shareable link
    await uploadPDF(pdfBlob);
  };

  const uploadPDF = async (pdfBlob) => {
    const bucketName = "pdfBucket";
    
    // get all the buckets
  
    
   // await axios.post(`${API_BASE_URL}/buckets`, { bucketName });

    // Prepare FormData
    const form = new FormData();
    // file name will file with current time
    // form.append("file", pdfBlob, "chat_transcript.pdf");
    form.append("file", pdfBlob, `chat_transcript_${new Date().getTime()}.pdf`);

    try {
      const response = await axios.post(`${API_BASE_URL}/buckets/${bucketName}/files`, form);
      console.log("File uploaded successfully:", response.data);
     
      // Generate and log shareable link
      const shareableLink = `${API_BASE_URL}/buckets/${bucketName}/files/chat_transcript_${new Date().getTime()}.pdf/download`;
      console.log("Shareable link:", shareableLink);
      // auto copy to clipboard
      navigator.clipboard.writeText(shareableLink);
      toast({
        title: "PDF Generated",
        description: `Your chat transcript PDF has been generated. You can download it from: ${shareableLink}`,
        status: "success",
        duration: 5000,
        isClosable: true,
      });
    } catch (error) {
      console.error("Error uploading PDF:", error.response ? error.response.data : error.message);
      toast({
        title: "Error",
        description: "Failed to upload PDF. Please try again.",
        status: "error",
        duration: 5000,
        isClosable: true,
      });
    }
  };

  return (
    <Box p={4} bg="gray.900">
      <Flex justifyContent="space-between" alignItems="center" mb={4}>
        <Heading size="lg" color="white">
          Defi AI Advisor
        </Heading>
        <Button onClick={exportToPDF} colorScheme="green">
          Share Chat PDF
        </Button>
      </Flex>

      <Grid templateColumns="repeat(2, 1fr)" gap={6}>
        {/* Left Column: Chat Section */}
        <GridItem colSpan={1}>
          <VStack spacing={4} align="stretch" height="calc(100vh - 100px)">
            <Box
              flex={1}
              overflowY="auto"
              bg="gray.700"
              p={3}
              borderRadius="md"
              borderWidth="1px"
              borderColor="gray.600"
            >
              {messages.map((msg, index) => (
                <Text
                  key={index}
                  bg={msg.sender === "user" ? "blue.600" : "green.600"}
                  color="white"
                  p={2}
                  borderRadius="md"
                  my={1}
                >
                  {msg.text}
                </Text>
              ))}
            </Box>
            <HStack>
              <Input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask about DeFi investments..."
                onKeyPress={(e) => e.key === "Enter" && handleSend()}
                bg="gray.800"
                color="white"
                _placeholder={{ color: "gray.400" }}
              />
              <Button onClick={handleSend} colorScheme="blue">
                Send
              </Button>
            </HStack>
          </VStack>
        </GridItem>

        {/* Right Column: News and Graph Section */}
        <GridItem colSpan={1}>
          <VStack spacing={4} align="stretch" height="calc(100vh - 100px)">
            {/* News Section */}
            <Heading size="md" color="white">
              Relevant News
            </Heading>
            <Box
              bg="gray.700"
              p={3}
              borderRadius="md"
              borderWidth="1px"
              borderColor="gray.600"
              minHeight={200}
              maxHeight="350px"
              overflowY="auto"
            >
              {news.map((article, index) => (
                <Box key={index} my={2}>
                  <Text fontWeight="bold" color="white">
                    {article.title}
                  </Text>
                  <Text fontSize="sm" color="gray.400">
                    {article.source.name} -{" "}
                    {new Date(article.publishedAt).toLocaleDateString()}
                  </Text>
                  <Text color="gray.300">{article.description}</Text>
                </Box>
              ))}
            </Box>

            {/* Price History Graph Section */}
            {priceHistory.length > 0 && (
              <Box
                bg="gray.700"
                p={3}
                borderRadius="md"
                borderWidth="1px"
                borderColor="gray.600"
                minHeight={400}
              >
                <Heading size="md" color="white" mb={4}>
                  Price History
                </Heading>
                <Line
                  data={{
                    labels: priceHistory.map((point) =>
                      new Date(point[0]).toLocaleDateString()
                    ),
                    datasets: [
                      {
                        label: `${selectedToken.toUpperCase()} Price (EUR)`,
                        data: priceHistory.map((point) => point[1]),
                        fill: false,
                        borderColor: "rgb(75, 192, 192)",
                        tension: 0.1,
                      },
                    ],
                  }}
                />
              </Box>
            )}
          </VStack>
        </GridItem>
      </Grid>
    </Box>
  );
}

export default IntegratedDeFiAdvisor;
